import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import HeaderComponent from "@/components/HeaderComponent";
import ProviderTheme from "@/components/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nico Schonfeld",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <HeaderComponent />
        {children}
      </body>
    </html>
  );
}
